"""Presence-only checking of arguments against an endpoint's published schema.

Only membership in the request model's ``required`` list is checked. The
published schemas are generated by pydantic, and pydantic accepts values its
own published schema rejects -- ``"8"`` coerces into an integer field rather
than failing -- so type, enum and format checks would refuse arguments the
application would have accepted and run.  An absent required key is the one
rule the two agree on.

A ``None`` value is not absence: a required field typed ``Optional[T]`` still
appears in ``required`` and accepts ``None``. Only a missing key counts.

Every lookup fails open. A schema that cannot be fetched, parsed or located
yields ``None`` -- "unknown" -- never "nothing required", so a network problem
can never turn into a rejected argument set.
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Optional

import httpx

OPENAPI_HOST = os.getenv("FAL_OPENAPI_HOST", "fal.ai")
OPENAPI_URL = f"https://{OPENAPI_HOST}/api/openapi/queue/openapi.json"
SCHEMA_FETCH_TIMEOUT = 10.0

_JSON_CONTENT_TYPE = "application/json"
_LOCAL_REF_PREFIX = "#/components/schemas/"

# Cached per process and keyed by endpoint id. A published schema belongs to a
# deployed revision, so this is stable for the life of a short-running program;
# a long-lived process that needs to see a redeploy calls `clear_schema_cache`.
_REQUIRED_CACHE: Dict[str, Optional[List[str]]] = {}


def clear_schema_cache() -> None:
    """Forget every cached schema lookup."""
    _REQUIRED_CACHE.clear()


def _resolve_schema(
    spec: Dict[str, Any], schema: Dict[str, Any]
) -> Optional[Dict[str, Any]]:
    """Follow a local ``$ref``, or return an inline schema unchanged.

    A ``$ref`` pointing outside this document is not followed: reporting
    "unknown" beats checking against the wrong model.
    """
    ref = schema.get("$ref")
    if not isinstance(ref, str):
        return schema
    if not ref.startswith(_LOCAL_REF_PREFIX):
        return None
    components = spec.get("components")
    if not isinstance(components, dict):
        return None
    schemas = components.get("schemas")
    if not isinstance(schemas, dict):
        return None
    resolved = schemas.get(ref[len(_LOCAL_REF_PREFIX) :])
    return resolved if isinstance(resolved, dict) else None


def required_arguments(spec: Dict[str, Any], application: str) -> Optional[List[str]]:
    """Required argument names for ``application``'s JSON request body.

    ``None`` means there is nothing to check against. That is deliberately
    distinct from ``[]``, which means the model declares no required fields --
    pydantic omits ``required`` entirely when every field has a default.
    """
    paths = spec.get("paths")
    if not isinstance(paths, dict):
        return None
    key = "/" + application.strip("/")
    path = paths.get(key)
    if path is None:
        path = paths.get(key + "/")
    if not isinstance(path, dict):
        return None
    post = path.get("post")
    if not isinstance(post, dict):
        return None
    body = post.get("requestBody")
    if not isinstance(body, dict):
        return None
    content = body.get("content")
    if not isinstance(content, dict):
        return None
    media = content.get(_JSON_CONTENT_TYPE)
    if not isinstance(media, dict):
        return None
    schema = media.get("schema")
    if not isinstance(schema, dict):
        return None
    model = _resolve_schema(spec, schema)
    if model is None:
        return None
    if "required" not in model:
        return []
    required = model["required"]
    if not isinstance(required, list):
        return None
    return [name for name in required if isinstance(name, str)]


def missing_required(arguments: Dict[str, Any], required: List[str]) -> List[str]:
    """Required names absent from ``arguments``, in declaration order."""
    return [name for name in required if name not in arguments]


def _extract(spec: Any, application: str) -> Optional[List[str]]:
    if not isinstance(spec, dict):
        return None
    return required_arguments(spec, application)


def fetch_required_arguments(application: str) -> Optional[List[str]]:
    """Required argument names for ``application``, or ``None`` if unknown.

    The published schema is public, so this needs no credentials.
    """
    if application in _REQUIRED_CACHE:
        return _REQUIRED_CACHE[application]
    required: Optional[List[str]] = None
    try:
        response = httpx.get(
            OPENAPI_URL,
            params={"endpoint_id": application},
            timeout=SCHEMA_FETCH_TIMEOUT,
            follow_redirects=True,
        )
        if response.status_code == 200:
            required = _extract(response.json(), application)
    except Exception:
        # Fail open: an unreachable or malformed schema must never be read as
        # "no arguments required".
        required = None
    _REQUIRED_CACHE[application] = required
    return required


async def fetch_required_arguments_async(
    application: str,
) -> Optional[List[str]]:
    """Async counterpart of :func:`fetch_required_arguments`."""
    if application in _REQUIRED_CACHE:
        return _REQUIRED_CACHE[application]
    required: Optional[List[str]] = None
    try:
        async with httpx.AsyncClient(
            timeout=SCHEMA_FETCH_TIMEOUT, follow_redirects=True
        ) as client:
            response = await client.get(
                OPENAPI_URL, params={"endpoint_id": application}
            )
            if response.status_code == 200:
                required = _extract(response.json(), application)
    except Exception:
        required = None
    _REQUIRED_CACHE[application] = required
    return required
