name: Integration Tests (fal)

on:
  push:
    branches: [main]
    paths:
      - "projects/fal/**"
      - ".github/workflows/fal-integration-tests.yml"

  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - "projects/fal/**"
      - ".github/workflows/fal-integration-tests.yml"

  schedule:
    - cron: "30 5 * * *" # every day at 5:30 UTC

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  integration:
    name: integration (${{ matrix.os }}, py ${{ matrix.python }}, ${{ matrix.deps }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        deps: ["pydantic==1.10.18", "pydantic==2.13.3"]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        exclude:
          - deps: "pydantic==2.13.3"
            python: "3.8"
          - deps: "pydantic==1.10.18"
            python: "3.9"
          - deps: "pydantic==1.10.18"
            python: "3.10"
          - deps: "pydantic==1.10.18"
            python: "3.11"
          - deps: "pydantic==1.10.18"
            python: "3.12"
          - deps: "pydantic==1.10.18"
            python: "3.13"
          - deps: "pydantic==1.10.18"
            python: "3.14"
        include:
          - os: windows-2022
            deps: "pydantic==2.13.3"
            python: "3.12"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -e 'projects/fal[test]' graphlib ${{ matrix.deps }}

      - name: Run integration tests
        env:
          FAL_KEY: ${{ secrets.FAL_KEY_PROD }}
          FAL_GRPC_HOST: api.alpha.fal.ai
          FAL_REST_HOST: rest.fal.ai
          FAL_RUN_HOST: fal.run
        run: pytest -n auto -v projects/fal/tests/integration -k "not test_regular_function_in_a_container_with_custom_image"

      - name: Run custom container image integration test
        env:
          FAL_KEY: ${{ secrets.FAL_KEY_PROD }}
          FAL_GRPC_HOST: api.alpha.fal.ai
          FAL_REST_HOST: rest.fal.ai
          FAL_RUN_HOST: fal.run
        run: pytest -v projects/fal/tests/integration/test_stability.py::test_regular_function_in_a_container_with_custom_image
