name: E2E Tests (fal)

on:
  push:
    branches: [main]

  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - "README.md"

  schedule:
    - cron: "30 5 * * *" # every day at 5:30 UTC

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e:
    name: e2e (${{ matrix.target }}, py ${{ matrix.python }}, ${{ matrix.deps }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        target: ["dev", "prod"]
        deps: ["pydantic==1.10.18", "pydantic==2.11.7"]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        include:
          - target: dev
            fal_grpc_host: api.fal.dev
            fal_run_host: run.fal.dev
          - target: prod
            fal_grpc_host: api.alpha.fal.ai
            fal_run_host: fal.run
        exclude:
          - deps: "pydantic==2.11.7"
            python: "3.8"
          - deps: "pydantic==1.10.18"
            python: "3.9"
          - deps: "pydantic==1.10.18"
            python: "3.10"
          - deps: "pydantic==1.10.18"
            python: "3.11"
          - deps: "pydantic==1.10.18"
            python: "3.12"
          - deps: "pydantic==1.10.18"
            python: "3.13"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -e 'projects/fal[test]' graphlib ${{ matrix.deps }}
          pip install -e 'projects/fal_client[test]'

      - name: Run e2e tests
        env:
          FAL_KEY: ${{ matrix.target == 'prod' && secrets.FAL_KEY_PROD || secrets.FAL_KEY_DEV }}
          FAL_GRPC_HOST: ${{ matrix.fal_grpc_host }}
          FAL_RUN_HOST: ${{ matrix.fal_run_host }}
        run: |
          pytest -n auto -v projects/fal/tests/e2e
