name: Run isolate-proto tests

on:
  push:
    branches:
      - main
    paths:
      - "projects/isolate_proto/**"
      - ".github/workflows/tests-isolate-proto.yml"
  pull_request:
    paths:
      - "projects/isolate_proto/**"
      - ".github/workflows/tests-isolate-proto.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -e 'projects/isolate_proto[test]'

      - name: Run tests
        run: |
          pytest -n auto -v projects/isolate_proto/tests
