name: Run fal-client tests

on:
  push:
    branches:
      - main
    paths:
      - "projects/fal_client/**"
      - ".github/workflows/tests-fal-client.yml"
  pull_request:
    paths:
      - "projects/fal_client/**"
      - ".github/workflows/tests-fal-client.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -e 'projects/fal_client[test]'
      - name: Run tests
        env:
          FAL_KEY: ${{ secrets.FAL_KEY_PROD }}
        run: |
          pytest projects/fal_client/tests
