name: Run fal-client tests

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install --upgrade pip wheel
        pip install -e 'projects/fal_client[test]'
    - name: Run tests
      env:
        FAL_KEY: ${{ secrets.FAL_KEY_PROD }}
      run: |
        pytest projects/fal_client/tests